### ISSUE TITLE
VAM on php

### ISSUE THREAD

**Issue by anwari26** [Progyan1997/Operational-Research#1]
hi @Progyan1997 can you create Vogel code from PHP?

**Comment by 0xTheProDev** [comment]
@anwari26 You can simply reuse the function implemented here, just by omitting type information, i.e., `int i` will become `$i` in PHP.

**Comment by anwari26** [comment]
ok i'll try my friend, but if i fell confused..can you make it for me :+1: 
thank you :smile:
